version: '3.8'
services:
  app:
    build:
      context: .
    container_name: expresso_app
    depends_on:
      - mongodb
      - redis
    restart: always
    ports:
      - '${PORT}:8000'
    working_dir: /app
    networks:
      - expresso_network

  mongodb:
    image: mongo:latest
    container_name: expresso_mongodb
    volumes:
      - './storage/mongo-volume:/data/db:rw'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    restart: always
    ports:
      - '27018:27017'
    networks:
      - expresso_network

  redis:
    image: 'redis:alpine'
    container_name: expresso_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6380:6379'
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      - expresso_network

networks:
  expresso_network:
    driver: bridge
